version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 8.0
    build:
        commands:
            - echo nothing to do yet
artifacts:
    files:
        - index.html
        - styles/*
        - images/*
        - favicon.ico
